-- Auth tables
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;

-- Curriculum tables
DROP TABLE IF EXISTS CURRICULUM_LESSON;
DROP TABLE IF EXISTS BLOCKS;
DROP TABLE IF EXISTS MODULES;
DROP TABLE IF EXISTS CURRICULUMS;
